services:
  backend:
    build: ./backend
    container_name: rails-api
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/rails
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: app_development

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - '5173:5173'
    stdin_open: true
    environment:
      REACT_APP_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
