---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/transactions":
    get:
      summary: list transactions
      tags:
      - Transactions
      description: Get all transactions
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    name:
                      type: string
                    date:
                      type: string
                    amount:
                      type: number
                    currency:
                      type: string
                    description:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    payment_method_id:
                      type: integer
                    category_id:
                      type: integer
        '401':
          description: unauthorized
    post:
      summary: create transaction
      tags:
      - Transactions
      description: Create a transaction
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: created
        '422':
          description: unprocessible entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Name of the transaction
                    date:
                      type: string
                      format: date
                      example: '2025-01-01'
                    amount:
                      type: number
                      example: 100.0
                    currency:
                      type: string
                      example: USD
                    description:
                      type: string
                      example: Description of the transaction
                    category_id:
                      type: integer
                      example: 1
                    payment_method_id:
                      type: integer
                      example: 1
                  required:
                  - name
                  - date
                  - amount
                  - currency
                  - category_id
                  - payment_method_id
  "/api/v1/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: Transaction ID
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      tags:
      - Transactions
      description: Get a transaction
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  name:
                    type: string
                  date:
                    type: string
                  amount:
                    type: number
                  currency:
                    type: string
                  description:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  payment_method_id:
                    type: integer
                  category_id:
                    type: integer
        '404':
          description: not found
        '401':
          description: unauthorized
    patch:
      summary: update transaction
      tags:
      - Transactions
      description: Update a transaction
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
        '422':
          description: unprocessible entity
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Updated name of the transaction
                    date:
                      type: string
                      format: date
                      example: '2025-01-01'
                    amount:
                      type: number
                      example: 100.0
                    currency:
                      type: string
                      example: USD
                    description:
                      type: string
                      example: Upated description of the transaction
                    category_id:
                      type: integer
                      example: 1
                    payment_method_id:
                      type: integer
                      example: 1
    delete:
      summary: delete transaction
      tags:
      - Transactions
      description: Delete a transaction
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '204':
          description: ok
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
